In [12]:
import numpy as np
import pandas as pd

In [13]:
try:
    temp_df = pd.read_csv('/content/IMDB Dataset (1).xls', engine='python',on_bad_lines='skip')
    print('File read successfully. First 5 rows:')
    print(temp_df.head())
except pd.errors.ParserError as e:
    print(f"Error reading file: {e}")
    print("This error (unexpected end of data) strongly suggests the file is either empty, truncated, or not a valid CSV.")
    print("Please check the '/content/IMDB Dataset (1).xls' file to ensure it's complete and properly formatted.")
    temp_df = None # Assign None or an empty DataFrame if you prefer to continue without data

File read successfully. First 5 rows:
                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [14]:
temp_df = pd.read_csv('/content/IMDB Dataset (1).xls', engine='python', on_bad_lines='skip')

In [15]:
df = temp_df.iloc[:10000]

In [16]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [17]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.'

In [18]:
df['review'].value_counts()

review
My favourite police series of all time turns to a TV-film. Does it work? Yes. Gee runs for mayor and gets shot. The Homicide "hall of fame" turns up. Pembleton and nearly all of the cops who ever played in this series. A lot of flashbacks helps you who hasn´t seen the TV-series but it amuses the fans too. The last five minutes solves another murder and at the very end even two of the dead cops turn up. And a short appearance from my favourite coroner Juliana Cox. This is a good film.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2
There are plenty of comments already posted saying exactly how I felt about this film so Ill keep it short.<br /><br />"The Grinch" I thought was marvellous - Jim Carrey is a truly talented, physical comedian as well as being a versatile clever actor (in my opinion). Mike Myers on the other hand gets his laughs by being annoying. I used to like him very much in his "Waynes World" and "So I Married an Axe Murderer" days - but Ive never been fond of Austin Powers and "the Cat In The Hat" has just finished me off. <br /><br />This film was horrible - the gags were horrible! inappropriate for children not only in adult content but in the fact that some of them were so dated they havent amused anyone for 50 years! The plot was messy, messy, messy! Its a shame really because the children were very likeable as was "Mom". They probably could have picked a better villain than Alec Baldwin - but he could have pulled it off if it weren't for Myers ugly, revolting over-acted portrayal of the Cat.<br /><br />I mean - did Myers even glance at a script? Was one written? The other actors seemed to have one - but the Cat just seemed to be winging it!<br /><br />On the other hand I would like to mention that the sets and props were marvellous!!! But unfortunately they cant save this film.<br /><br />Poor Dr Seuss - the man was a genius! Dont ruin his reputation by adapting his work in a such a lazy, messy way!!!<br /><br />1/10                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               2
Ik know it is impossible to keep all details of a book in a movie. But this movie has changed nearly everything without any reason. Furthermore many changes have made the story illogical. A few examples: 1) in the movie "Paul Renauld" really meets Poriot before he dies (in the book Poirot only gets a letter), telling him he is afraid to be killed. This is completely stupid because if Renaulds plan would have succeeded, Poirot would have known that the dead man would not have been Renauld.(Poirot was in the morgue when Mrs Renauld identified the victim). 2) The movie has "combined" two persons into one! "Cinderella" has been removed by the movie. The girl Hastings falls in love with and the ex-girlfriend of Jack Renauld are one person in the movie! Why for god's sake? 3)Hastings finds the victims cause he is such a bad golf player. Totally unfunny and stupid. 4) The movie tells secrets much too early (for example at the very beginning). So you know things you shouldn't know. 5) The murderer gets shot at the end by a person who doesn't exists in the book. Perhaps because the person ("cinderella") who stops the murderer does not exists in the movie. 6)The book is very complex. The movie takes only about 90 minutes. Sure it is difficult to include all the necessary details but it is impossible if you include stupid things which were not in the book and have no meaning (e.g. bicycle race).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         2
Beautiful film, pure Cassavetes style. Gena Rowland gives a stunning performance of a declining actress, dealing with success, aging, loneliness...and alcoholism. She tries to escape her own subconscious ghosts, embodied by the death spectre of a young girl. Acceptance of oneself, of human condition, though its overall difficulties, is the real purpose of the film. The parallel between the theatrical sequences and the film itself are puzzling: it's like if the stage became a way out for the Heroin. If all american movies could only be that top-quality, dealing with human relations on an adult level, not trying to infantilize and standardize feelings... One of the best dramas ever. 10/10.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2
Quite what the producers of this appalling adaptation were trying to do is impossible to fathom.<br /><br />A group of top quality actors, in the main well cast (with a couple of notable exceptions), who give pretty good performances. Penelope Keith is perfect as Aunt Louise and equally good is Joanna Lumley as Diana. All do well with the scripts they were given.<br /><br />So much for the good. The average would include the sets. Nancherrow is nothing like the house described in the book, although bizarrely the house they use for the Dower House looks remarkably like it. It is clear then that the Dower House is far too big. In the later parts, the writers decided to bring the entire story back to the UK, presumably to save money, although with a little imagination I have no doubt they could have recreated Ceylon.<br /><br />Now to the bad. The screenplay. This is such an appallingly bad adaptation is hard to find words to condemn it. Edward does not die in the battle of Britain but survives, blinded. He makes a brief appearance then commits suicide - why?? Loveday has changed from the young woman totally in love with Gus to a sensible farmer's wife who can give up the love her life with barely a tear (less emotional than Brief Encounter). Gus, a man besotted and passionately in love, is prepared to give up his love without complaint. Walter (Mudge in the book) turns from a shallow unfaithful husband to a devoted family man. Jess is made into a psychologically disturbed young woman who won't speak. Aunt Biddy still has a drink problem but now without any justification. The Dower House is occupied by the army for no obvious reason other than a very short scene with Jess who has a fear of armed soldiers. Whilst Miss Mortimer's breasts are utterly delightful, I could not see how their display on several occasions moved the plot forward. The delightfully named Nettlebed becomes the mundane Dobson. The word limit prevents me from continuing the list.<br /><br />There is a sequel (which I lost all interest in watching after this nonsense) and I wonder if the changes were made to create the follow on story. It is difficult to image that Rosamunde Pilcher would have approved this grotesque perversion of her book; presumably she lost her control when the rights were purchased.    2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ..
Hilarious film, I had a great time watching it. The star (Cuneyt Arkin, sometimes credited as Steve Arkin) is a popular actor from Turkey. He has played in lots of tough-guy roles, epic-sword films, and romances. It was fun to see him with an international cast and some real lousy looking pair of gloves. If I remember it was also dubbed in English which made things even more funnier. (kinda like seeing John Wayne speak Turkish).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
This is by far the best stand-up routine I have ever seen. John Leguizamo's one man show tells the supposed story of his life in a barrage of lines and situations. By far better than any other comedy out there.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1

In [19]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(17)

In [21]:
df.drop_duplicates(inplace=True)

/tmp/ipython-input-3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
# basic preprocessing
# lowercase

In [24]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [25]:
df['review'] = df['review'].apply(remove_tags)

/tmp/ipython-input-2336150696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)

In [26]:
df

                                                 review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

In [27]:
df['review'] = df['review'].apply(lambda x:x.lower())

/tmp/ipython-input-740760900.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())

In [28]:
df

                                                 review sentiment
0     one of the other reviewers has mentioned that ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought this was a wonderful way to spend ti...  positive
3     basically there's a family where a little boy ...  negative
4     petter mattei's "love in the time of money" is...  positive
...                                                 ...       ...
9995  fun, entertaining movie about wwii german spy ...  positive
9996  give me a break. how can anyone say that this ...  negative
9997  this movie is a bad movie. but after watching ...  negative
9998  this is a movie that was probably made to ente...  negative
9999  smashing film about film-making. shows the int...  positive

[9983 rows x 2 columns]

In [29]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
/tmp/ipython-input-640380602.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [30]:
df

                                                 review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     wonderful little production. filming technique...  positive
2     thought wonderful way spend time hot summer we...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. anyone say "good hockey movie"? kn...  negative
9997  movie bad movie. watching endless series bad h...  negative
9998  movie probably made entertain middle school, e...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [31]:
x = df.iloc[:,0:1]
y = df['sentiment']

In [32]:
x

                                                 review
0     one reviewers mentioned watching 1 oz episode ...
1     wonderful little production. filming technique...
2     thought wonderful way spend time hot summer we...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. anyone say "good hockey movie"? kn...
9997  movie bad movie. watching endless series bad h...
9998  movie probably made entertain middle school, e...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [33]:
y

0       positive
1       positive
2       positive
3       negative
4       positive
          ...
9995    positive
9996    negative
9997    negative
9998    negative
9999    positive
Name: sentiment, Length: 9983, dtype: object

In [34]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [35]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [36]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [37]:
x_train.shape

(7986, 1)

In [38]:
y_train.shape

(7986,)

In [39]:
# Applying BOW
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [40]:
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [41]:
x_train_bow.shape

(7986, 48282)

In [42]:
x_test_bow.shape

(1997, 48282)

In [43]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

In [44]:
gnb.fit(x_train_bow, y_train)

GaussianNB()

In [45]:
y_pred = gnb.predict(x_test_bow)

In [46]:
from sklearn.metrics import accuracy_score, confusion_matrix

accuracy_score(y_test, y_pred)

0.6324486730095142

In [47]:
confusion_matrix(y_test, y_pred)
#

array([[717, 235],
       [499, 546]])

In [48]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

In [49]:
rfc.fit(x_train_bow, y_train)
y_pred = rfc.predict(x_test_bow)
accuracy_score(y_test, y_pred)

0.8412618928392589

In [50]:
cv = CountVectorizer(max_features=3000)
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [51]:
rf = RandomForestClassifier()
rf.fit(x_train_bow, y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test, y_pred)

0.8352528793189785

In [58]:
cv = CountVectorizer( ngram_range=(1,2))

In [1]:
x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(x_train_bow, y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test, y_pred)

NameError: name 'cv' is not defined

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

cv = CountVectorizer(max_features=3000, ngram_range=(1,2))

x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

rf = RandomForestClassifier()
rf.fit(x_train_bow, y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test, y_pred)

NameError: name 'x_train' is not defined

Using Tf_idf

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [53]:
x_train_tfidf = tfidf.fit_transform(x_train['review']).toarray()
x_test_tfidf = tfidf.transform(x_test['review']).toarray()

In [54]:
rf = RandomForestClassifier()

rf.fit(x_train_tfidf, y_train)
y_pred = rf.predict(x_test_tfidf)

accuracy_score(y_test, y_pred)

0.8407611417125689